when:
  - event: push
    branch: main
steps:
  build_image:
    image: quay.io/buildah/stable
    privileged: true
    environment:
      REGISTRY: harbor.anrostech.com
      IMAGE_BASE: anros/crm-front
      REGISTRY_USER:
        from_secret: registry_user
      REGISTRY_PASS:
        from_secret: registry_pass
      VITE_API_URL: https://api.anrostech.com/api/crm
      VITE_ENV: production
    commands:
      - IMAGE_TAG=${CI_PIPELINE_CREATED}
      - |
        echo "Logging into Harbor..."
        echo "Branch: $CI_COMMIT_BRANCH"
        buildah login $REGISTRY -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

        buildah build --build-arg VITE_API_URL=$VITE_API_URL --build-arg VITE_ENV=$VITE_ENV --layers --cache-from $REGISTRY/$IMAGE_BASE --cache-to $REGISTRY/$IMAGE_BASE -t $REGISTRY/$IMAGE_BASE:$IMAGE_TAG .
        buildah push $REGISTRY/$IMAGE_BASE:$IMAGE_TAG

  update_deployment_repo:
    image: alpine/git
    depends_on:
      - build_image
    environment:
      GIT_TOKEN:
        from_secret: git_token
      GIT_OWNER: marknguyenanl
      GIT_REPO: rr
      GIT_URL: github.com
    commands:
      - |
        IMAGE_TAG=${CI_PIPELINE_CREATED}
        BRANCH=${CI_COMMIT_BRANCH}

        echo "Clone repo"
        git clone https://$GIT_TOKEN@$GIT_URL/$GIT_OWNER/$GIT_REPO
        cd rr

        echo "Git identity"
        git config user.name "anrostech-bot"
        git config user.email "ci@anrostech.com"


        echo "Create branch safely"
        git fetch origin $BRANCH || true
        git checkout -B $BRANCH origin/$BRANCH || git checkout -B $BRANCH
        git pull --rebase origin $BRANCH || true

        FILES=$(grep -rl "name: crm-front" . || true)
        for f in $FILES; do
          sed -i -E 's|(image: harbor\.anrostech\.com/anros/crm-front:)[^[:space:]]+|\1'"$IMAGE_TAG"'|' "$f"
        done
        if git diff --quiet; then
          echo "✅ No changes detected, skipping commit"
          exit 0
        fi

        git add $FILES
        git commit -m "CI: Update crm-front image to $IMAGE_TAG"

        echo "Push branch"
        git push origin $BRANCH
