steps:
  build_image:
    image: quay.io/podman/stable
    privileged: true
    environment:
      REGISTRY: harbor.anrostech.com
      IMAGE_BASE: anros/crm-front
      IMAGE_TAG: latest
      REGISTRY_USER:
        from_secret: registry_user
      REGISTRY_PASS:
        from_secret: registry_pass
    commands:
      - echo "Logging into Harbor..."
      - podman login $REGISTRY -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

      - podman pull $REGISTRY/$IMAGE_BASE || true
      - podman build --cache-from $REGISTRY/anros/cache --cache-to $REGISTRY/anros/cache -t $REGISTRY/$IMAGE_BASE:$IMAGE_TAG .
      - podman push $REGISTRY/$IMAGE_BASE:$IMAGE_TAG
