# Minimal clone to satisfy CLI
clone:
  git:
    image: woodpeckerci/plugin-git
    depth: 1
    tags: true
    skip_verify: false
    partial: true

# Steps
steps:

  # 1️⃣ Install dependencies
  install_deps:
    image: node:20
    commands:
      - echo "Installing dependencies..."
      - npm install
  # 2️⃣ Build Vue app
  build_vue_app:
    image: node:20
    commands:
      - echo "Building Vue app..."
      - npm run build
    depends_on:
      - install_deps

  # 3️⃣ Build and push container image
  build_image:
    image: ghcr.io/genuinetools/img:latest
    commands:
      - echo "Building container image..."
      - img build -t harbor.anrostech.com/anros/crm-anros-frontend:latest -f ./Containerfile .
      - echo 'Harbor12345' | img login harbor.anrostech.com --username 'admin' --password-stdin
      - img push harbor.anrostech.com/anros/crm-anros-frontend:latest
    depends_on:
      - build_vue_app
