clone:
  git:
    image: woodpeckerci/plugin-git
    depth: 1
    tags: true
    # This line forces Woodpecker to skip anything in .gitignore
    skip_verify: false
    partial: true        # ← this enables .gitignore + .woodpecker.yml ignoring

steps:
  install_deps:
    image: node:20
    commands:
      # Install dependencies
      - npm install
    volumes:
      - name: npm-cache
        path: /root/.npm

  build_vue_app:
    image: node:20
    commands:
      # Build Vue app
      - npm run build
    depends_on:
      - install_deps
    volumes:
      - name: npm-cache
        path: /root/.npm
      - name: vue-dist
        path: /app/dist

  build_image:
    image: ghcr.io/genuinetools/img:latest
    commands:
      # Build a container image using the dist folder
      - img build -t harbor.anrostech.com/anros/crm-anros-frontend:latest -f ./Containerfile .
      # Push to registry
      - echo $HARBOR_PASSWORD | img login my-registry --username $HARBOR_USERNAME --password-stdin
      - img push my-registry/my-vue-app:latest
    depends_on:
      - build_vue_app
    secrets: [HARBOR_USERNAME, HARBOR_PASSWORD]
    volumes:
      - name: vue-dist
        path: /app/dist

# Volumes for caching
volumes:
  npm-cache:
    temp: {}
  vue-dist:
    temp: {}
