steps:
  build_image:
    image: quay.io/podman/stable
    privileged: true
    environment:
      REGISTRY: harbor.anrostech.com
    commands:
      - echo "Logging into Harbor..."
      - podman login $REGISTRY -u admin -p Harbor12345
      - dnf install -y --setopt=install_weak_deps=False python3 python3-pip git
      - pip3 install --no-cache-dir podman-compose

      - echo "Building images via docker-compose..."
      - podman-compose -f docker-compose.yml build

      - echo "Tagging and pushing images..."
      - podman-compose -f docker-compose.yml push
