# .woodpecker.yaml – NO secrets required (plain username + password)
steps:
  build-and-push:
    image: woodpeckerci/plugin-kaniko:4
    settings:
      registry: https://harbor.anrostech.com
      username: admin                  # ← your real Harbor username here
      password: Harbor12345            # ← your real Harbor password here (plain text)
      repo: anros/crm-anros-front
      tag: latest
      dockerfile: Dockerfile
      cache: true
      cache_ttl: 168h                  # optional, keeps build fast
      insecure_registry: harbor.anrostech.com   # remove this line if you have a valid certificate

when:
  event: [ push, tag, manual ]
  branch: [ main ]   # change to master if your default branch is called master
