steps:
  build_image:
    image: quay.io/buildah/stable
    privileged: true
    environment:
      REGISTRY: harbor.anrostech.com
      IMAGE_BASE: anros/crm-front
      IMAGE_TAG: latest
      REGISTRY_USER:
        from_secret: registry_user
      REGISTRY_PASS:
        from_secret: registry_pass
    commands:
      - echo "Logging into Harbor..."
      - buildah login $REGISTRY -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

      - buildah pull $REGISTRY/$IMAGE_BASE || true
      - buildah build --layers --cache-from $REGISTRY/$IMAGE_BASE --cache-to $REGISTRY/$IMAGE_BASE -t $REGISTRY/$IMAGE_BASE:$IMAGE_TAG .
      - buildah push $REGISTRY/$IMAGE_BASE:$IMAGE_TAG
  update_deployment_repo:
    image: alpine:3.18
    depends_on:
      - build_image
    environment:
      GIT_TOKEN:
        from_secret: git_token
    commands:
      # 1️⃣ Install git, curl, bash, and yq
      - apk add --no-cache git curl bash
      - curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq
      - chmod +x /usr/bin/yq
      - curl -L https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
      - apk add --no-cache gh

      # 2️⃣ Clone repo
      - git clone https://$GIT_TOKEN@gitea.anrostech.com/mark/rr.git
      - cd rr
      - CI_COMMIT_SHA=$(git rev-parse --short HEAD)

      # 3️⃣ Configure git
      - git config user.name "woodpecker-bot"
      - git config user.email "ci@anrostech.com"

      # 4️⃣ Pull latest main
      - git checkout main
      - git pull --rebase origin main

      # 5️⃣ Create a new branch for this CI run

      # 6️⃣ Find files containing crm-front
      - FILES=$(grep -rl "name: crm-front" .)

      # 7️⃣ Update Deployment container images
      - |
        for f in $FILES; do
          yq -i '
            select(.kind=="Deployment")
            | .spec.template.spec.containers[]
            | select(.name=="crm-front")
            | .image = "harbor.anrostech.com/anros/crm-front:'"$CI_COMMIT_SHA"'"
          ' "$f"
        done

      - git add $FILES
      - git commit -m "CI: Update crm-front image to ${CI_COMMIT_SHA}" || echo "No changes to commit"

      - git push origin main
