# .woodpecker.yaml – final version (no confusion)
steps:
  build-and-push-kaniko:
    image: gcr.io/kaniko-project/executor:latest
    commands:
      - /kaniko/executor \
          --context=${CI_WORKSPACE} \
          --dockerfile=${CI_WORKSPACE}/Dockerfile \
          --destination=harbor.anrostech.com/anros/crm-anros-front:latest \
          --username=${HARBOR_USERNAME} \
          --password=${HARBOR_PASSWORD} \
          --cache=true \
          --cache-ttl=168h \
          --insecure-registry=harbor.anrostech.com   # remove if your cert is valid
    environment:
      HARBOR_USERNAME:
        from_secret: harbor_username   # ← secret name = harbor_username
      HARBOR_PASSWORD:
        from_secret: harbor_password   # ← secret name = harbor_password

when:
  event: [ push, tag, manual ]
  branch: [ main ]
