steps:
  kaniko:
    image: gcr.io/kaniko-project/executor:latest
    commands:
      - /kaniko/executor \
          --context=. \
          --dockerfile=Dockerfile \
          --destination=harbor.anrostech.com/anros/crm-anros-front:latest \
          --username=${HARBOR_USERNAME} \
          --password=${HARBOR_PASSWORD} \
          --insecure-registry=harbor.anrostech.com \
          --cache=true
    secrets: [ admin, anrostech ]

when:
  event: [ push, tag, manual ]
  branch: [ main ]
