steps:
  build_image:
    image: quay.io/podman/stable
    environment:
      REGISTRY: harbor.anrostech.com
      IMAGE: harbor.anrostech.com/anros/crm-anros-frontend:latest
    commands:
      - echo "Logging into Harbor..."
      - podman login $REGISTRY -u admin -p Harbor12345

      - echo "Building image..."
      - podman build -t $IMAGE -f Dockerfile .

      - echo "Pushing image..."
      - podman push $IMAGE
