
pipeline:
  install:
    image: node:20-alpine
    commands:
      - apk add --no-cache git
      - npm ci
    volumes:
      - /cache/npm:/root/.npm

  build:
    image: node:20-alpine
    depends_on: [install]
    commands:
      - npx nx build frontend --configuration=production
    volumes:
      - /cache/nx:/workspace/.nx/cache

  # Optional: Docker image build
  image-build:
    image: quay.io/buildah/stable
    depends_on: [build]
    environment:
      STORAGE_DRIVER: "vfs"
      BUILDAH_ISOLATION: "chroot"
    commands:
      - buildah bud -t harbor.anrostech.com/crm-anros-frontend:latest .
    volumes:
      - /var/lib/containers:/var/lib/containers

