steps:
  build_image:
    image: quay.io/podman/stable
    privileged: true
    environment:
      REGISTRY: harbor.anrostech.com
      IMAGE_NAME: anros/crm-front
      IMAGE_TAG: latest
      REGISTRY_USER:
        from_secret: registry_user
      REGISTRY_PASS:
        from_secret: registry_pass
    commands:
      - echo "Logging into Harbor..."
      - podman login $REGISTRY -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

      - podman build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
      - podman push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
