steps:
  build_and_push:
    image: gcr.io/kaniko-project/executor:latest
    environment:
      DOCKER_CONFIG: /kaniko/.docker/
    commands:
      - |
        echo "{\"auths\":{\"harbor.anrostech.com\":{\"username\":\"admin\",\"password\":\"Harbor12345\"}}}" \
        > /kaniko/.docker/config.json

      - echo "Building & pushing image with Kaniko..."
      - /kaniko/executor \
          --context $CI_WORKSPACE \
          --dockerfile $CI_WORKSPACE/Dockerfile \
          --destination harbor.anrostech.com/anros/crm-anros-frontend:latest \
          --cleanup
