clone:
  git:
    image: woodpeckerci/plugin-git
    depth: 1
    tags: true
    # This line forces Woodpecker to skip anything in .gitignore
    skip_verify: false
    partial: true        # ← this enables .gitignore + .woodpecker.yml ignoring

steps:
  build-and-push:
    image: woodpeckerci/plugin-buildah   # official plugin, rootless by default
    settings:
      # Registry login (plain text – no secrets if you don't want them)
      username: admin
      password: Harbor12345

      # Registry & image
      registry: https://harbor.anrostech.com
      repo: anros/crm-anros-front
      tag: latest

      # Build options (optimized multi-stage Vue build)
      dockerfile: Dockerfile
      context: .                     # build context = repo root
      build_args:
        - NODE_ENV=production

      # Speed & security
      cache: true                    # uses Buildah layer cache (very fast after first build)
      no_cache: false
      pull: true                     # always pull base images

      # For self-signed Harbor cert
      insecure: true                 # equivalent to --tls-verify=false

      # Extra tags (optional but recommended)
      extra_tags:
        - ${CI_COMMIT_SHA:0:8}       # e.g. abc12345
        - ${CI_COMMIT_TAG:-latest}   # uses git tag if present

when:
  event: [ push, tag, manual ]
  branch: [ main ]
